name: aws
runtime: python3.11

# environment:
#   DB_USER: ${env:DB_USER}
#   DB_PASSWORD: ${env:DB_PASSWORD}
#   DB_HOST: ${env:DB_HOST}
#   DB_NAME: ${env:DB_NAME}
#   OPEN_WEATHER_API_URL: ${env:OPEN_WEATHER_API_URL}
#   OPEN_WEATHER_API_KEY: ${env:OPEN_WEATHER_API_KEY}
#   DEEPL_API_KEY: ${env:DEEPL_API_KEY}
#   JWT_SECRET_KEY: ${env:JWT_SECRET_KEY}